# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wordWithText.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WorkWithText(object):
    def setupUi(self, WorkWithText):
        WorkWithText.setObjectName("WorkWithText")
        WorkWithText.resize(1023, 789)
        self.addInDictionary = QtWidgets.QPushButton(WorkWithText)
        self.addInDictionary.setGeometry(QtCore.QRect(860, 230, 131, 26))
        self.addInDictionary.setObjectName("addInDictionary")
        self.OK = QtWidgets.QPushButton(WorkWithText)
        self.OK.setGeometry(QtCore.QRect(910, 750, 97, 26))
        self.OK.setObjectName("OK")
        self.loadTagAndTag = QtWidgets.QPushButton(WorkWithText)
        self.loadTagAndTag.setEnabled(False)
        self.loadTagAndTag.setGeometry(QtCore.QRect(860, 90, 131, 26))
        self.loadTagAndTag.setObjectName("loadTagAndTag")
        self.tabWidget = QtWidgets.QTabWidget(WorkWithText)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 811, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.workWithText = QtWidgets.QTableWidget(self.tab)
        self.workWithText.setGeometry(QtCore.QRect(0, 0, 801, 681))
        self.workWithText.setObjectName("workWithText")
        self.workWithText.setColumnCount(3)
        self.workWithText.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.workWithText.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workWithText.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.workWithText.setHorizontalHeaderItem(2, item)
        self.workWithText.horizontalHeader().setDefaultSectionSize(215)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tagAndTag = QtWidgets.QTableWidget(self.tab_2)
        self.tagAndTag.setGeometry(QtCore.QRect(0, 0, 651, 681))
        self.tagAndTag.setObjectName("tagAndTag")
        self.tagAndTag.setColumnCount(2)
        self.tagAndTag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tagAndTag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tagAndTag.setHorizontalHeaderItem(1, item)
        self.tagAndTag.horizontalHeader().setDefaultSectionSize(318)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.wordTag = QtWidgets.QTableWidget(self.tab_3)
        self.wordTag.setGeometry(QtCore.QRect(0, 0, 651, 681))
        self.wordTag.setObjectName("wordTag")
        self.wordTag.setColumnCount(2)
        self.wordTag.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wordTag.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wordTag.setHorizontalHeaderItem(1, item)
        self.wordTag.horizontalHeader().setDefaultSectionSize(322)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tagFrequency = QtWidgets.QTableWidget(self.tab_4)
        self.tagFrequency.setGeometry(QtCore.QRect(0, 0, 801, 681))
        self.tagFrequency.setObjectName("tagFrequency")
        self.tagFrequency.setColumnCount(3)
        self.tagFrequency.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tagFrequency.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tagFrequency.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tagFrequency.setHorizontalHeaderItem(2, item)
        self.tagFrequency.horizontalHeader().setDefaultSectionSize(215)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.wordFreqTable = QtWidgets.QTableWidget(self.tab_5)
        self.wordFreqTable.setGeometry(QtCore.QRect(0, 0, 651, 681))
        self.wordFreqTable.setObjectName("wordFreqTable")
        self.wordFreqTable.setColumnCount(2)
        self.wordFreqTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wordFreqTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wordFreqTable.setHorizontalHeaderItem(1, item)
        self.wordFreqTable.horizontalHeader().setDefaultSectionSize(322)
        self.tabWidget.addTab(self.tab_5, "")
        self.saveChangesAboutText = QtWidgets.QPushButton(WorkWithText)
        self.saveChangesAboutText.setGeometry(QtCore.QRect(860, 60, 131, 26))
        self.saveChangesAboutText.setObjectName("saveChangesAboutText")
        self.wordTagButton = QtWidgets.QPushButton(WorkWithText)
        self.wordTagButton.setEnabled(False)
        self.wordTagButton.setGeometry(QtCore.QRect(860, 120, 131, 26))
        self.wordTagButton.setObjectName("wordTagButton")
        self.tagFreqButton = QtWidgets.QPushButton(WorkWithText)
        self.tagFreqButton.setEnabled(False)
        self.tagFreqButton.setGeometry(QtCore.QRect(860, 150, 131, 26))
        self.tagFreqButton.setObjectName("tagFreqButton")
        self.wordFrequencyButton = QtWidgets.QPushButton(WorkWithText)
        self.wordFrequencyButton.setEnabled(False)
        self.wordFrequencyButton.setGeometry(QtCore.QRect(860, 180, 131, 26))
        self.wordFrequencyButton.setObjectName("wordFrequencyButton")
        self.comboBox = QtWidgets.QComboBox(WorkWithText)
        self.comboBox.setGeometry(QtCore.QRect(860, 430, 85, 27))
        self.comboBox.setObjectName("comboBox")
        self.addInDictionary.raise_()
        self.OK.raise_()
        self.loadTagAndTag.raise_()
        self.saveChangesAboutText.raise_()
        self.tabWidget.raise_()
        self.wordTagButton.raise_()
        self.tagFreqButton.raise_()
        self.wordFrequencyButton.raise_()
        self.comboBox.raise_()

        self.retranslateUi(WorkWithText)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WorkWithText)

    def retranslateUi(self, WorkWithText):
        _translate = QtCore.QCoreApplication.translate
        WorkWithText.setWindowTitle(_translate("WorkWithText", "Work with text"))
        self.addInDictionary.setText(_translate("WorkWithText", "Add in dictionary"))
        self.OK.setText(_translate("WorkWithText", "OK"))
        self.loadTagAndTag.setText(_translate("WorkWithText", "Tag and tag"))
        item = self.workWithText.horizontalHeaderItem(0)
        item.setText(_translate("WorkWithText", "Word"))
        item = self.workWithText.horizontalHeaderItem(1)
        item.setText(_translate("WorkWithText", "Tag"))
        item = self.workWithText.horizontalHeaderItem(2)
        item.setText(_translate("WorkWithText", "Explanation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WorkWithText", "Work with text"))
        item = self.tagAndTag.horizontalHeaderItem(0)
        item.setText(_translate("WorkWithText", "Tag/Tag"))
        item = self.tagAndTag.horizontalHeaderItem(1)
        item.setText(_translate("WorkWithText", "Repetitions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WorkWithText", "Tag and tag"))
        item = self.wordTag.horizontalHeaderItem(0)
        item.setText(_translate("WorkWithText", "Word/Tag"))
        item = self.wordTag.horizontalHeaderItem(1)
        item.setText(_translate("WorkWithText", "Frequency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WorkWithText", "Word/Tag"))
        item = self.tagFrequency.horizontalHeaderItem(0)
        item.setText(_translate("WorkWithText", "Tag"))
        item = self.tagFrequency.horizontalHeaderItem(1)
        item.setText(_translate("WorkWithText", "Frequency"))
        item = self.tagFrequency.horizontalHeaderItem(2)
        item.setText(_translate("WorkWithText", "Explanation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("WorkWithText", "Tag/Frequency"))
        item = self.wordFreqTable.horizontalHeaderItem(0)
        item.setText(_translate("WorkWithText", "Word"))
        item = self.wordFreqTable.horizontalHeaderItem(1)
        item.setText(_translate("WorkWithText", "Frequency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("WorkWithText", "Word/Frequency"))
        self.saveChangesAboutText.setText(_translate("WorkWithText", "Save changes"))
        self.wordTagButton.setText(_translate("WorkWithText", "Word/Tag"))
        self.tagFreqButton.setText(_translate("WorkWithText", "Tag/Freq"))
        self.wordFrequencyButton.setText(_translate("WorkWithText", "Word/Freq"))
